import React from "react";
import Intro from "./components/intro.jsx";
import Projet from "./components/Projet.jsx";
import TableExperience from "./components/tableExperience.jsx";
import { HelmetProvider } from "react-helmet-async";
import MaintenanceBanner from "./components/MaintenanceBanner.jsx";
import Resume from "./components/resume.jsx";
import Chrono from "./components/Chrono.jsx";

function App() {
  return (
    <>
      <HelmetProvider>
        <title>Nowak Louis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <link rel="icon" href="/favicon.png" />
      </HelmetProvider>
      <div className="min-h-screen p-4 bg-[#013328] bg-cover bg-fixed">
        <MaintenanceBanner />
        <Intro />
        <div className="mt-32">
          <Resume />
        </div>
        <div className="mt-32">
          <Chrono />
        </div>
        <TableExperience />
        <Projet />
      </div>
    </>
  );
}

export default App;
