import React from "react";
import AboutMe from "./components/aboutMe.jsx";
import BackHeader from "./components/BackHeader.jsx";
import Intro from "./components/intro.jsx";
import LineLeft from "./components/LineLeft.jsx";
import LineRight from "./components/LineRight.jsx";
import NavBar from "./components/navBar.jsx";
import Projet from "./components/Projet.jsx";
import TableExperience from "./components/tableExperience.jsx";
import Stack from "@mui/material/Stack";
import { HelmetProvider } from "react-helmet-async";
import ThemeProvider from "./styles/theme";
import MaintenanceBanner from "./components/MaintenanceBanner.jsx";

function App() {
  return (
    <>
      <HelmetProvider>
        <title>Nowak Louis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </HelmetProvider>
      <Stack
        sx={{
          minHeight: "100vh",
          padding: "1rem",
          backgroundColor: "#013328",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <ThemeProvider>
          <NavBar />
          <MaintenanceBanner />
          <Intro />
          <AboutMe />
          <TableExperience />
          <Projet />
          <LineLeft />
          <LineRight />
          <BackHeader />
        </ThemeProvider>
      </Stack>
    </>
  );
}

export default App;
